---
# tasks file for the role that updates time servers

- name: Initialize an empty list for formatted servers
  ansible.builtin.set_fact:
    timesync_servers_formatted: []

- name: Prepare the source list of servers
  ansible.builtin.set_fact:
    _source_list: "{{ user_ntp_servers.split(',') if user_ntp_servers is string else user_ntp_servers }}"

- name: Build the formatted list of NTP servers
  ansible.builtin.set_fact:
    timesync_servers_formatted: "{{ timesync_servers_formatted + [{'hostname': item | trim, 'iburst': true}] }}"
  loop: "{{ _source_list }}"
  # This iterative approach is more robust than a single complex Jinja2 expression
  # and avoids potential parsing errors.

- name: Set Time Server Configuration using the RHEL System Role
  ansible.builtin.include_role:
    name: redhat.rhel_system_roles.timesync
  vars:
    # Use the newly formatted variable here
    timesync_ntp_servers: "{{ timesync_servers_formatted }}"
    timesync_timezone: "{{ user_timezone }}"
    timesync_transactional_update_reboot_ok: "{{ user_timesync_transactional_update_reboot_ok | default(false) }}"

- name: Print Updated Time Sync Status
  ansible.builtin.command:
    cmd: timedatectl status
  changed_when: false
  register: timesync_status

- name: Display Updated Time Sync Status
  ansible.builtin.debug:
    msg: |
      =====================================
      Time Sync Status:
      =====================================
      {{ timesync_status.stdout }}
      =====================================
