- name: Convert NTP servers variable to the required list format
  ansible.builtin.set_fact:
    timesync_servers_formatted: >-
      {{
        user_ntp_servers.split(',') |
        map('trim') |
        map('regex_replace', '^(.*)$', {'hostname': '\\1', 'iburst': true}) |
        list
      }}

- name: Set Time Server Configuration using the RHEL System Role
  ansible.builtin.include_role:
    name: redhat.rhel_system_roles.timesync
  vars:
    # Use the newly formatted variable here
    timesync_ntp_servers: "{{ timesync_servers_formatted }}"
    timesync_timezone: "{{ user_timezone }}"
    timesync_transactional_update_reboot_ok: "{{ user_timesync_transactional_update_reboot_ok | default(false) }}"

- name: Print Updated Time Sync Status
  ansible.builtin.command:
    cmd: timedatectl status
  changed_when: false
  register: timesync_status

- name: Display Updated Time Sync Status
  ansible.builtin.debug:
    msg: |
      =====================================
      Time Sync Status:
      =====================================
      {{ timesync_status.stdout }}
      =====================================
